Ext.define('usercontrol.store.res',
	{
		extend:'Ext.data.Store',
		model:'usercontrol.model.resModel',
		autoLoad:true,
		pageSize:100,
		proxy:
			{
				type:'ajax',
				url:'/usercontrol/data/getres',
				reader:
					{
						type:'json',
						root:'data',
						
					},
					simpleSortMode:true
			},
			sorters:
				[
				 	{
				 		property:'resource_id',
				 		direction:'ASC'
				 	}
				]
});