Ext.define('usercontrol.view.addactionView',
	{
		extend:'Ext.container.Container',
		requires:['usercontrol.component.addAction'],
		alias:'widget.addactionView',
		items:
			[
				{
					xtype:'container',
					autoFit:true,
					items:
						[
							{
								xtype:'addAction',
								layout:'vbox',
								width:400,
							}
						]
				}
			],
	})