Ext.define('usercontrol.view.searchBoxView',
	{
		extend:'Ext.container.Container',
		requires:['usercontrol.component.searchBox'],
		alias:'widget.searchBoxView',
		items:
			[
				{
					xtype:'container',
					autoFit:true,
					items:
						[
							{
								xtype:'search',
								layout:'vbox',
								width:400,
							}
						]
				}
			],
	})