Ext.define('usercontrol.view.usersForm',
	{
		extend:'Ext.container.Container',
		requires:['usercontrol.component.employeeForm'],
		alias:'widget.forms',
		items:
			[
				{
					xtype:'container',
					autoFit:true,
					items:
						[
							{
								xtype:'employee',
								layout:'vbox',
								width:375,
							}
						]
				}
			],
	})