Ext.define('usercontrol.view.addresourceView',
	{
		extend:'Ext.container.Container',
		requires:['usercontrol.component.addResources'],
		alias:'widget.addresourceView',
		items:
			[
				{
					xtype:'container',
					autoFit:true,
					items:
						[
							{
								xtype:'addResources',
								layout:'vbox',
								width:400,
							}
						]
				}
			],
	})