Ext.define('usercontrol.component.resourceForm',
	{
		extend:'Ext.form.Panel',
		alias:'widget.resources',
		url:'/usercontrol/data/addres',
		title:'Resource',
		requires:'usercontrol.component.createUserButtons',
		items:
			[
				{
					xtype:'panel',
					columnWidth:.4,
					padding:'0 0 0 5',
					bodyPadding:10,
					items:
						[
							{
								xtype:'textfield',
								fieldLabel:'Resource ID:',
								name:'resource_id',
								id:'resource_id',
								readOnly:true,
								
							},
							{
								xtype:'textfield',
								fieldLabel:'Name:',
								name:'name',
								id:'resource_name'
							},
							{
								xtype:'textfield',
								fieldLabel:'URL',
								name:'url',
								id:'url'
							},
							{
								xtype:'textfield',
								fieldLabel:'Controller:',
								name:'controllers',
								id:'controller'
							}
						],
						dockedItems:[{
							xtype:'toolbar',
							dock:'bottom',
							ui:'footer',
							items:[{
								xtype:'createUserButtons'
							}]
				}
			]
				}
				]
	});